#!/bin/bash
[ -z "${PUSHOVER_KEY}" ] && echo "PUSHOVER_KEY is not set" && exit 1
[ -z "${PUSHOVER_TOKEN}" ] && echo "PUSHOVER_TOKEN is not set" && exit 1
[ -z "${PLC_IP}" ] && echo "PLC_IP is not set" && exit 1

cmdline="plcwatchd -k ${PUSHOVER_KEY} -t ${PUSHOVER_TOKEN} -i ${PLC_IP}  -l /dev/stdout ${CLI_ARGS}"
echo "execute: ${cmdline}"
$cmdline

